environments:
  development:
    server: "dev-server.example.com"
    port: 8000
    replicas: 1
    resources:
      cpu: "500m"
      memory: "512Mi"
    
  staging:
    server: "staging-server.example.com"
    port: 8000
    replicas: 2
    resources:
      cpu: "1000m"
      memory: "1Gi"
    
  production:
    server: "prod-server.example.com"
    port: 8000
    replicas: 3
    resources:
      cpu: "2000m"
      memory: "2Gi"

deployment_strategy:
  type: "rolling"
  max_surge: 1
  max_unavailable: 0

healthcheck:
  path: "/health"
  interval: 30
  timeout: 10
  retries: 3

monitoring:
  enabled: true
  metrics_port: 9090
  
notifications:
  email:
    enabled: true
    recipients:
      - "kumarhvsandeep@gmail.com"
  slack:
    enabled: false
    webhook_url: ""
